[pytest]
testpaths = tests
pythonpath = .. .
addopts = -ra --strict-markers -p no:cacheprovider --cov=meadowpy --cov-config=dev/.coveragerc --cov-report=term-missing --cov-report=xml:dev/coverage.xml
