"""Built-in Python example library for beginners.

Organized by category, each example has a title, description,
and fully-commented source code.
"""

EXAMPLE_CATEGORIES = [
    {
        "name": "Basics",
        "icon": "\U0001F331",
        "examples": [
            {
                "name": "Variables & Types",
                "desc": "Storing data in variables and checking types",
                "code": (
                    '# Variables & Types\n'
                    '# A variable is a name that stores a value.\n'
                    '# Python figures out the type automatically.\n'
                    '\n'
                    '# Text is called a "string" (str)\n'
                    'name = "Alice"\n'
                    '\n'
                    '# Whole numbers are "integers" (int)\n'
                    'age = 14\n'
                    '\n'
                    '# Numbers with decimals are "floats" (float)\n'
                    'height = 5.6\n'
                    '\n'
                    '# True/False values are "booleans" (bool)\n'
                    'likes_python = True\n'
                    '\n'
                    '# type() tells you what kind of data a variable holds\n'
                    'print(f"name = {name} (type: {type(name).__name__})")\n'
                    'print(f"age = {age} (type: {type(age).__name__})")\n'
                    'print(f"height = {height} (type: {type(height).__name__})")\n'
                    'print(f"likes_python = {likes_python} (type: {type(likes_python).__name__})")\n'
                    '\n'
                    '# You can change a variable\'s value at any time\n'
                    'age = age + 1\n'
                    'print(f"\\nHappy birthday! Now age = {age}")\n'
                ),
            },
            {
                "name": "String Formatting",
                "desc": "Different ways to build and format text",
                "code": (
                    '# String Formatting\n'
                    '# Strings are text — you can combine and format them.\n'
                    '\n'
                    'first = "Ada"\n'
                    'last = "Lovelace"\n'
                    '\n'
                    '# Method 1: Concatenation (joining with +)\n'
                    'full_name = first + " " + last\n'
                    'print("Concatenation:", full_name)\n'
                    '\n'
                    '# Method 2: f-strings (recommended!) — put variables inside {}\n'
                    'print(f"f-string: {first} {last}")\n'
                    '\n'
                    '# f-strings can contain expressions too\n'
                    'price = 9.99\n'
                    'quantity = 3\n'
                    'print(f"Total: ${price * quantity:.2f}")  # :.2f means 2 decimal places\n'
                    '\n'
                    '# Useful string methods\n'
                    'message = "  Hello, World!  "\n'
                    'print(f"Upper: {message.upper()}")       # ALL CAPS\n'
                    'print(f"Lower: {message.lower()}")       # all lowercase\n'
                    'print(f"Strip: \'{message.strip()}\'")     # remove extra spaces\n'
                    'print(f"Replace: {message.replace(\'World\', \'Python\')}")\n'
                    'print(f"Length: {len(message)} characters")\n'
                ),
            },
            {
                "name": "Type Conversion",
                "desc": "Converting between numbers, strings, and more",
                "code": (
                    '# Type Conversion\n'
                    '# Sometimes you need to convert data from one type to another.\n'
                    '\n'
                    '# input() always gives you a string, even if you type a number\n'
                    'text = input("Enter a number: ")\n'
                    'print(f"You typed: {text} (type: {type(text).__name__})")\n'
                    '\n'
                    '# int() converts to a whole number\n'
                    'number = int(text)\n'
                    'print(f"As integer: {number} (type: {type(number).__name__})")\n'
                    '\n'
                    '# float() converts to a decimal number\n'
                    'decimal = float(text)\n'
                    'print(f"As float: {decimal} (type: {type(decimal).__name__})")\n'
                    '\n'
                    '# str() converts anything to a string\n'
                    'age = 25\n'
                    'age_text = str(age)\n'
                    'print(f"As string: \'{age_text}\' (type: {type(age_text).__name__})")\n'
                    '\n'
                    '# bool() converts to True/False\n'
                    '# 0, empty string, None, and empty lists are False\n'
                    '# Everything else is True\n'
                    'print(f"\\nbool(1) = {bool(1)}")\n'
                    'print(f"bool(0) = {bool(0)}")\n'
                    'print(f\'bool("hello") = {bool("hello")}\')\n'
                    'print(f\'bool("") = {bool("")}\')\n'
                ),
            },
            {
                "name": "Math Operations",
                "desc": "Arithmetic, rounding, and the math module",
                "code": (
                    '# Math Operations\n'
                    '# Python can do all kinds of math.\n'
                    '\n'
                    '# Basic arithmetic\n'
                    'a, b = 17, 5\n'
                    'print(f"{a} + {b} = {a + b}")     # Addition\n'
                    'print(f"{a} - {b} = {a - b}")     # Subtraction\n'
                    'print(f"{a} * {b} = {a * b}")     # Multiplication\n'
                    'print(f"{a} / {b} = {a / b}")     # Division (gives a float)\n'
                    'print(f"{a} // {b} = {a // b}")   # Floor division (whole number)\n'
                    'print(f"{a} % {b} = {a % b}")     # Modulo (remainder)\n'
                    'print(f"{a} ** {b} = {a ** b}")   # Power (17 to the 5th)\n'
                    '\n'
                    '# Rounding\n'
                    'pi = 3.14159265\n'
                    'print(f"\\nround(pi, 2) = {round(pi, 2)}")\n'
                    'print(f"round(pi, 4) = {round(pi, 4)}")\n'
                    '\n'
                    '# The math module has more advanced functions\n'
                    'import math\n'
                    'print(f"\\nmath.sqrt(144) = {math.sqrt(144)}")   # Square root\n'
                    'print(f"math.floor(3.7) = {math.floor(3.7)}")  # Round down\n'
                    'print(f"math.ceil(3.2) = {math.ceil(3.2)}")    # Round up\n'
                    'print(f"math.pi = {math.pi}")                  # Pi constant\n'
                ),
            },
            {
                "name": "User Input",
                "desc": "Reading and validating keyboard input",
                "code": (
                    '# User Input\n'
                    '# input() pauses the program and waits for the user to type.\n'
                    '# It always returns a string, so convert if you need a number.\n'
                    '\n'
                    '# Basic input\n'
                    'name = input("What is your name? ")\n'
                    'print(f"Nice to meet you, {name}!")\n'
                    '\n'
                    '# Getting a number with validation\n'
                    '# If the user types something that isn\'t a number, handle it.\n'
                    'while True:\n'
                    '    answer = input("\\nPick a number between 1 and 10: ")\n'
                    '    if not answer.isdigit():\n'
                    '        print("That\'s not a number! Try again.")\n'
                    '        continue\n'
                    '    num = int(answer)\n'
                    '    if 1 <= num <= 10:\n'
                    '        break\n'
                    '    print("Out of range! Must be 1-10.")\n'
                    '\n'
                    'print(f"You picked {num}!")\n'
                    '\n'
                    '# Building a simple menu\n'
                    'print("\\n--- Favorite Color ---")\n'
                    'print("1. Red")\n'
                    'print("2. Blue")\n'
                    'print("3. Green")\n'
                    'choice = input("Choose 1, 2, or 3: ")\n'
                    '\n'
                    'colors = {"1": "Red", "2": "Blue", "3": "Green"}\n'
                    'color = colors.get(choice, "Unknown")\n'
                    'print(f"You chose: {color}")\n'
                ),
            },
            {
                "name": "Comments & Readability",
                "desc": "Writing clear code with comments and naming",
                "code": (
                    '# Comments & Readability\n'
                    '# Good code is code that humans can read easily.\n'
                    '\n'
                    '# === Single-line comments ===\n'
                    '# This is a comment — Python ignores it.\n'
                    '# Use comments to explain WHY, not WHAT.\n'
                    '\n'
                    '# Bad comment (describes what the code already says):\n'
                    'x = 5  # Set x to 5\n'
                    '\n'
                    '# Good comment (explains the reasoning):\n'
                    'max_retries = 5  # Server times out after 5 failed attempts\n'
                    '\n'
                    '# === Multi-line strings as documentation ===\n'
                    'def calculate_bmi(weight_kg, height_m):\n'
                    '    """Calculate Body Mass Index.\n'
                    '\n'
                    '    Args:\n'
                    '        weight_kg: Weight in kilograms\n'
                    '        height_m: Height in meters\n'
                    '\n'
                    '    Returns:\n'
                    '        BMI as a float, rounded to 1 decimal.\n'
                    '    """\n'
                    '    bmi = weight_kg / (height_m ** 2)\n'
                    '    return round(bmi, 1)\n'
                    '\n'
                    '# === Good variable names ===\n'
                    '# Bad:  a = 70; b = 1.75\n'
                    '# Good:\n'
                    'weight = 70\n'
                    'height = 1.75\n'
                    'result = calculate_bmi(weight, height)\n'
                    'print(f"BMI for {weight}kg at {height}m: {result}")\n'
                    '\n'
                    '# You can read the docstring with help()\n'
                    'help(calculate_bmi)\n'
                ),
            },
        ],
    },
    {
        "name": "Control Flow",
        "icon": "\U0001F500",
        "examples": [
            {
                "name": "If / Elif / Else",
                "desc": "Making decisions in your code",
                "code": (
                    '# If / Elif / Else\n'
                    '# Use "if" to run code only when a condition is true.\n'
                    '\n'
                    'age = int(input("Enter your age: "))\n'
                    '\n'
                    '# "if" checks the first condition\n'
                    '# "elif" (else if) checks another condition if the first was false\n'
                    '# "else" runs if nothing above was true\n'
                    'if age < 0:\n'
                    '    print("That\'s not a valid age!")\n'
                    'elif age < 13:\n'
                    '    print("You\'re a child.")\n'
                    'elif age < 18:\n'
                    '    print("You\'re a teenager.")\n'
                    'elif age < 65:\n'
                    '    print("You\'re an adult.")\n'
                    'else:\n'
                    '    print("You\'re a senior.")\n'
                    '\n'
                    '# Comparison operators:\n'
                    '#   ==  equal to          !=  not equal to\n'
                    '#   <   less than          >   greater than\n'
                    '#   <=  less or equal      >=  greater or equal\n'
                    '\n'
                    '# You can combine conditions with "and", "or", "not"\n'
                    'has_ticket = True\n'
                    'if age >= 13 and has_ticket:\n'
                    '    print("\\nYou can enter the movie!")\n'
                    'elif not has_ticket:\n'
                    '    print("\\nYou need a ticket first.")\n'
                    'else:\n'
                    '    print("\\nSorry, you\'re too young for this movie.")\n'
                ),
            },
            {
                "name": "For Loops",
                "desc": "Repeating code a set number of times",
                "code": (
                    '# For Loops\n'
                    '# A "for" loop repeats code for each item in a sequence.\n'
                    '\n'
                    '# Loop through a list of items\n'
                    'fruits = ["apple", "banana", "cherry"]\n'
                    'for fruit in fruits:\n'
                    '    print(f"I like {fruit}!")\n'
                    '\n'
                    '# range() generates a sequence of numbers\n'
                    '# range(5) gives: 0, 1, 2, 3, 4\n'
                    'print("\\nCounting to 5:")\n'
                    'for i in range(1, 6):  # range(1, 6) gives: 1, 2, 3, 4, 5\n'
                    '    print(f"  {i}")\n'
                    '\n'
                    '# enumerate() gives you both the index and the item\n'
                    'colors = ["red", "green", "blue"]\n'
                    'print("\\nColors list:")\n'
                    'for index, color in enumerate(colors):\n'
                    '    print(f"  {index}: {color}")\n'
                    '\n'
                    '# Nested loops (a loop inside a loop)\n'
                    'print("\\nMultiplication table (1-5):")\n'
                    'for row in range(1, 6):\n'
                    '    for col in range(1, 6):\n'
                    '        # end=" " prints without a newline\n'
                    '        print(f"{row * col:4}", end="")\n'
                    '    print()  # New line after each row\n'
                ),
            },
            {
                "name": "While Loops",
                "desc": "Repeating code until a condition is met",
                "code": (
                    '# While Loops\n'
                    '# A "while" loop repeats as long as a condition is true.\n'
                    '\n'
                    '# Simple countdown\n'
                    'count = 5\n'
                    'print("Countdown:")\n'
                    'while count > 0:\n'
                    '    print(f"  {count}...")\n'
                    '    count -= 1  # Same as: count = count - 1\n'
                    'print("  Liftoff!")\n'
                    '\n'
                    '# "break" exits the loop immediately\n'
                    '# "continue" skips to the next iteration\n'
                    'print("\\nType \'quit\' to exit, or a number to double it:")\n'
                    'while True:  # Runs forever until we break\n'
                    '    text = input("> ")\n'
                    '\n'
                    '    if text == "quit":\n'
                    '        print("Goodbye!")\n'
                    '        break  # Exit the loop\n'
                    '\n'
                    '    # Try to convert to a number\n'
                    '    # If it fails, "continue" skips back to the top\n'
                    '    if not text.lstrip("-").isdigit():\n'
                    '        print("That\'s not a number. Try again.")\n'
                    '        continue  # Skip the rest, go back to top\n'
                    '\n'
                    '    number = int(text)\n'
                    '    print(f"{number} * 2 = {number * 2}")\n'
                ),
            },
            {
                "name": "Try / Except",
                "desc": "Handling errors gracefully",
                "code": (
                    '# Try / Except\n'
                    '# Errors happen! try/except lets you handle them\n'
                    '# instead of crashing your program.\n'
                    '\n'
                    '# Without try/except, this would crash:\n'
                    '#   int("hello")  -> ValueError!\n'
                    '\n'
                    '# With try/except, we catch the error:\n'
                    'try:\n'
                    '    num = int(input("Enter a number: "))\n'
                    '    print(f"Your number doubled: {num * 2}")\n'
                    'except ValueError:\n'
                    '    print("That wasn\'t a valid number!")\n'
                    '\n'
                    '# You can catch different error types\n'
                    'def safe_divide(a, b):\n'
                    '    try:\n'
                    '        result = a / b\n'
                    '    except ZeroDivisionError:\n'
                    '        print("Cannot divide by zero!")\n'
                    '        return None\n'
                    '    except TypeError:\n'
                    '        print("Both arguments must be numbers!")\n'
                    '        return None\n'
                    '    else:\n'
                    '        # Runs only if NO exception happened\n'
                    '        print(f"{a} / {b} = {result}")\n'
                    '        return result\n'
                    '    finally:\n'
                    '        # Runs ALWAYS, error or not\n'
                    '        print("--- division attempted ---")\n'
                    '\n'
                    'print()\n'
                    'safe_divide(10, 3)\n'
                    'print()\n'
                    'safe_divide(10, 0)\n'
                    'print()\n'
                    'safe_divide(10, "two")\n'
                ),
            },
            {
                "name": "Logical Operators",
                "desc": "Combining conditions with and, or, not",
                "code": (
                    '# Logical Operators\n'
                    '# Combine multiple conditions to make complex decisions.\n'
                    '\n'
                    '# "and" — both must be True\n'
                    '# "or"  — at least one must be True\n'
                    '# "not" — flips True to False (and vice versa)\n'
                    '\n'
                    '# === A theme park ride checker ===\n'
                    'print("=== Theme Park Ride Checker ===")\n'
                    'height = int(input("Your height in cm: "))\n'
                    'age = int(input("Your age: "))\n'
                    'has_parent = input("Is a parent with you? (y/n): ").lower() == "y"\n'
                    '\n'
                    '# Roller coaster: must be tall enough AND old enough\n'
                    'can_ride_coaster = height >= 140 and age >= 10\n'
                    '\n'
                    '# Bumper cars: tall enough OR has a parent\n'
                    'can_ride_bumper = height >= 120 or has_parent\n'
                    '\n'
                    '# Haunted house: old enough AND NOT too young\n'
                    'can_ride_haunted = age >= 13 and not (age < 8)\n'
                    '\n'
                    'print(f"\\nRoller Coaster: {\'Yes!\' if can_ride_coaster else \'No\'}")\n'
                    'print(f"Bumper Cars:    {\'Yes!\' if can_ride_bumper else \'No\'}")\n'
                    'print(f"Haunted House:  {\'Yes!\' if can_ride_haunted else \'No\'}")\n'
                    '\n'
                    '# === Short-circuit evaluation ===\n'
                    '# Python stops checking as soon as it knows the result.\n'
                    'items = []\n'
                    '# "and" stops at the first False value\n'
                    'if items and items[0] == "apple":\n'
                    '    print("First item is apple")\n'
                    'else:\n'
                    '    print("\\nList is empty or doesn\'t start with apple")\n'
                    '# This is safe! Python never checks items[0] because items is empty.\n'
                ),
            },
        ],
    },
    {
        "name": "Data Structures",
        "icon": "\U0001F4E6",
        "examples": [
            {
                "name": "Lists",
                "desc": "Ordered collections you can change",
                "code": (
                    '# Lists\n'
                    '# A list holds multiple items in order.\n'
                    '# Lists use square brackets: []\n'
                    '\n'
                    '# Create a list\n'
                    'colors = ["red", "green", "blue"]\n'
                    'print("Original:", colors)\n'
                    '\n'
                    '# Access items by index (starts at 0)\n'
                    'print(f"First: {colors[0]}")   # red\n'
                    'print(f"Last: {colors[-1]}")    # blue (-1 = last item)\n'
                    '\n'
                    '# Add items\n'
                    'colors.append("yellow")          # Add to end\n'
                    'colors.insert(1, "orange")        # Insert at position 1\n'
                    'print(f"After adding: {colors}")\n'
                    '\n'
                    '# Remove items\n'
                    'colors.remove("green")            # Remove by value\n'
                    'popped = colors.pop()             # Remove and return last item\n'
                    'print(f"Popped: {popped}")\n'
                    'print(f"After removing: {colors}")\n'
                    '\n'
                    '# Slicing — get a sub-list\n'
                    'numbers = [0, 1, 2, 3, 4, 5]\n'
                    'print(f"\\nnumbers[1:4] = {numbers[1:4]}")  # [1, 2, 3]\n'
                    'print(f"numbers[:3] = {numbers[:3]}")      # [0, 1, 2]\n'
                    'print(f"numbers[3:] = {numbers[3:]}")      # [3, 4, 5]\n'
                    '\n'
                    '# Useful list functions\n'
                    'nums = [3, 1, 4, 1, 5, 9, 2]\n'
                    'print(f"\\nLength: {len(nums)}")\n'
                    'print(f"Sorted: {sorted(nums)}")\n'
                    'print(f"Sum: {sum(nums)}")\n'
                    'print(f"Min: {min(nums)}, Max: {max(nums)}")\n'
                ),
            },
            {
                "name": "Dictionaries",
                "desc": "Key-value pairs for organizing data",
                "code": (
                    '# Dictionaries\n'
                    '# A dictionary stores key-value pairs.\n'
                    '# Think of it like a real dictionary: word -> definition.\n'
                    '# Dictionaries use curly braces: {}\n'
                    '\n'
                    '# Create a dictionary\n'
                    'student = {\n'
                    '    "name": "Alice",\n'
                    '    "age": 14,\n'
                    '    "grade": "A",\n'
                    '    "hobbies": ["reading", "coding"]\n'
                    '}\n'
                    '\n'
                    '# Access values by key\n'
                    'print(f"Name: {student[\'name\']}")\n'
                    'print(f"Age: {student[\'age\']}")\n'
                    '\n'
                    '# .get() is safer — returns None if key doesn\'t exist\n'
                    'print(f"Email: {student.get(\'email\', \'not set\')}")\n'
                    '\n'
                    '# Add or change values\n'
                    'student["email"] = "alice@example.com"  # Add new key\n'
                    'student["age"] = 15                      # Update existing key\n'
                    '\n'
                    '# Loop through a dictionary\n'
                    'print("\\nAll student info:")\n'
                    'for key, value in student.items():\n'
                    '    print(f"  {key}: {value}")\n'
                    '\n'
                    '# Check if a key exists\n'
                    'if "name" in student:\n'
                    '    print(f"\\nStudent name is {student[\'name\']}")\n'
                    '\n'
                    '# Useful dictionary methods\n'
                    'print(f"\\nKeys: {list(student.keys())}")\n'
                    'print(f"Values: {list(student.values())}")\n'
                ),
            },
            {
                "name": "Tuples & Sets",
                "desc": "Immutable sequences and unique collections",
                "code": (
                    '# Tuples & Sets\n'
                    '# Two more useful data structures in Python.\n'
                    '\n'
                    '# === TUPLES ===\n'
                    '# A tuple is like a list but cannot be changed (immutable).\n'
                    '# Tuples use parentheses: ()\n'
                    'point = (3, 7)\n'
                    'print(f"Point: {point}")\n'
                    'print(f"X: {point[0]}, Y: {point[1]}")\n'
                    '\n'
                    '# Tuple unpacking — assign each item to a variable\n'
                    'x, y = point\n'
                    'print(f"Unpacked: x={x}, y={y}")\n'
                    '\n'
                    '# Tuples are great for returning multiple values\n'
                    'rgb = ("red", "green", "blue")\n'
                    'for color in rgb:\n'
                    '    print(f"  Color: {color}")\n'
                    '\n'
                    '# === SETS ===\n'
                    '# A set holds unique items (no duplicates).\n'
                    '# Sets use curly braces: {} (but no key:value pairs)\n'
                    'fruits = {"apple", "banana", "cherry", "apple"}  # Duplicate removed!\n'
                    'print(f"\\nFruits set: {fruits}")\n'
                    '\n'
                    '# Add and remove\n'
                    'fruits.add("mango")\n'
                    'fruits.discard("banana")  # Safe remove (no error if missing)\n'
                    'print(f"Updated: {fruits}")\n'
                    '\n'
                    '# Set operations\n'
                    'a = {1, 2, 3, 4}\n'
                    'b = {3, 4, 5, 6}\n'
                    'print(f"\\na = {a}")\n'
                    'print(f"b = {b}")\n'
                    'print(f"Union (a | b): {a | b}")          # All items\n'
                    'print(f"Intersection (a & b): {a & b}")    # Common items\n'
                    'print(f"Difference (a - b): {a - b}")      # In a but not b\n'
                ),
            },
            {
                "name": "Nested Structures",
                "desc": "Lists of dictionaries and complex data",
                "code": (
                    '# Nested Structures\n'
                    '# Real data often combines lists and dictionaries.\n'
                    '\n'
                    '# A list of dictionaries — like a mini database\n'
                    'students = [\n'
                    '    {"name": "Alice", "grade": 92, "subject": "Math"},\n'
                    '    {"name": "Bob", "grade": 85, "subject": "Science"},\n'
                    '    {"name": "Charlie", "grade": 78, "subject": "Math"},\n'
                    '    {"name": "Diana", "grade": 95, "subject": "Science"},\n'
                    '    {"name": "Eve", "grade": 88, "subject": "Math"},\n'
                    ']\n'
                    '\n'
                    '# Print all students\n'
                    'print("All students:")\n'
                    'for s in students:\n'
                    '    print(f"  {s[\'name\']:10} {s[\'subject\']:8} Grade: {s[\'grade\']}")\n'
                    '\n'
                    '# Filter: only Math students\n'
                    'math_students = [s for s in students if s["subject"] == "Math"]\n'
                    'print(f"\\nMath students: {len(math_students)}")\n'
                    '\n'
                    '# Find the highest grade\n'
                    'top = max(students, key=lambda s: s["grade"])\n'
                    'print(f"Top student: {top[\'name\']} with {top[\'grade\']}")\n'
                    '\n'
                    '# Calculate average grade\n'
                    'avg = sum(s["grade"] for s in students) / len(students)\n'
                    'print(f"Class average: {avg:.1f}")\n'
                    '\n'
                    '# Group by subject\n'
                    'by_subject = {}\n'
                    'for s in students:\n'
                    '    subj = s["subject"]\n'
                    '    if subj not in by_subject:\n'
                    '        by_subject[subj] = []\n'
                    '    by_subject[subj].append(s["name"])\n'
                    '\n'
                    'print("\\nGrouped by subject:")\n'
                    'for subj, names in by_subject.items():\n'
                    '    print(f"  {subj}: {\\", \\".join(names)}")\n'
                ),
            },
            {
                "name": "Stacks & Queues",
                "desc": "Using lists as stacks and queues",
                "code": (
                    '# Stacks & Queues\n'
                    '# Two common patterns for processing data in order.\n'
                    '\n'
                    '# === STACK (Last In, First Out) ===\n'
                    '# Think of a stack of plates — you add and remove from the top.\n'
                    'print("=== Stack (LIFO) ===")\n'
                    'stack = []\n'
                    '\n'
                    '# Push items onto the stack\n'
                    'for item in ["A", "B", "C", "D"]:\n'
                    '    stack.append(item)\n'
                    '    print(f"  Push {item} -> {stack}")\n'
                    '\n'
                    '# Pop items off the stack (reverse order!)\n'
                    'print("\\nPopping:")\n'
                    'while stack:\n'
                    '    item = stack.pop()  # Removes and returns the LAST item\n'
                    '    print(f"  Pop {item} -> {stack}")\n'
                    '\n'
                    '# === QUEUE (First In, First Out) ===\n'
                    '# Think of a line at a store — first person in line is served first.\n'
                    'from collections import deque  # Efficient for queues\n'
                    '\n'
                    'print("\\n=== Queue (FIFO) ===")\n'
                    'queue = deque()\n'
                    '\n'
                    '# Enqueue — add to the back\n'
                    'for person in ["Alice", "Bob", "Charlie"]:\n'
                    '    queue.append(person)\n'
                    '    print(f"  Join: {person} -> {list(queue)}")\n'
                    '\n'
                    '# Dequeue — remove from the front\n'
                    'print("\\nServing:")\n'
                    'while queue:\n'
                    '    person = queue.popleft()  # Removes the FIRST item\n'
                    '    print(f"  Serve: {person} -> {list(queue)}")\n'
                ),
            },
        ],
    },
    {
        "name": "Functions",
        "icon": "\U00002699",
        "examples": [
            {
                "name": "Defining Functions",
                "desc": "Creating reusable blocks of code",
                "code": (
                    '# Defining Functions\n'
                    '# A function is a reusable block of code.\n'
                    '# Use "def" to define one.\n'
                    '\n'
                    '# A simple function with no parameters\n'
                    'def say_hello():\n'
                    '    print("Hello there!")\n'
                    '\n'
                    'say_hello()  # Call the function\n'
                    '\n'
                    '# A function with parameters (inputs)\n'
                    'def greet(name):\n'
                    '    print(f"Hello, {name}!")\n'
                    '\n'
                    'greet("Alice")\n'
                    'greet("Bob")\n'
                    '\n'
                    '# A function that returns a value\n'
                    'def add(a, b):\n'
                    '    return a + b\n'
                    '\n'
                    'result = add(3, 5)\n'
                    'print(f"\\n3 + 5 = {result}")\n'
                    '\n'
                    '# Default parameter values\n'
                    'def power(base, exponent=2):\n'
                    '    """Raise base to exponent. Defaults to squaring."""\n'
                    '    return base ** exponent\n'
                    '\n'
                    'print(f"\\npower(4) = {power(4)}")        # Uses default: 4^2\n'
                    'print(f"power(2, 10) = {power(2, 10)}")  # Override: 2^10\n'
                    '\n'
                    '# Functions can return multiple values (as a tuple)\n'
                    'def min_max(numbers):\n'
                    '    return min(numbers), max(numbers)\n'
                    '\n'
                    'lowest, highest = min_max([4, 7, 1, 9, 3])\n'
                    'print(f"\\nMin: {lowest}, Max: {highest}")\n'
                ),
            },
            {
                "name": "List Comprehensions",
                "desc": "Building lists in a single line",
                "code": (
                    '# List Comprehensions\n'
                    '# A compact way to create lists from other lists.\n'
                    '\n'
                    '# The long way — using a for loop:\n'
                    'squares = []\n'
                    'for x in range(1, 6):\n'
                    '    squares.append(x ** 2)\n'
                    'print(f"Squares (loop): {squares}")\n'
                    '\n'
                    '# The short way — list comprehension:\n'
                    '# [expression for item in iterable]\n'
                    'squares = [x ** 2 for x in range(1, 6)]\n'
                    'print(f"Squares (comp): {squares}")\n'
                    '\n'
                    '# With a condition — only include even numbers\n'
                    'evens = [x for x in range(1, 11) if x % 2 == 0]\n'
                    'print(f"\\nEvens 1-10: {evens}")\n'
                    '\n'
                    '# Transform strings\n'
                    'words = ["hello", "world", "python"]\n'
                    'upper_words = [w.upper() for w in words]\n'
                    'print(f"Uppercased: {upper_words}")\n'
                    '\n'
                    '# Practical example: Fahrenheit to Celsius\n'
                    'fahrenheit = [32, 68, 77, 100, 212]\n'
                    'celsius = [round((f - 32) * 5 / 9, 1) for f in fahrenheit]\n'
                    'print(f"\\nFahrenheit: {fahrenheit}")\n'
                    'print(f"Celsius:    {celsius}")\n'
                ),
            },
            {
                "name": "Recursion",
                "desc": "Functions that call themselves",
                "code": (
                    '# Recursion\n'
                    '# A recursive function calls itself to solve smaller\n'
                    '# pieces of the same problem.\n'
                    '\n'
                    '# === Factorial ===\n'
                    '# 5! = 5 * 4 * 3 * 2 * 1 = 120\n'
                    'def factorial(n):\n'
                    '    # Base case: stop recursing\n'
                    '    if n <= 1:\n'
                    '        return 1\n'
                    '    # Recursive case: n! = n * (n-1)!\n'
                    '    return n * factorial(n - 1)\n'
                    '\n'
                    'print(f"5! = {factorial(5)}")\n'
                    'print(f"10! = {factorial(10)}")\n'
                    '\n'
                    '# === Fibonacci ===\n'
                    '# Each number is the sum of the two before it\n'
                    '# 0, 1, 1, 2, 3, 5, 8, 13, 21, ...\n'
                    'def fibonacci(n):\n'
                    '    if n <= 0:\n'
                    '        return 0\n'
                    '    if n == 1:\n'
                    '        return 1\n'
                    '    return fibonacci(n - 1) + fibonacci(n - 2)\n'
                    '\n'
                    'print("\\nFibonacci sequence:")\n'
                    'for i in range(10):\n'
                    '    print(f"  fib({i}) = {fibonacci(i)}")\n'
                    '\n'
                    '# === Countdown with recursion ===\n'
                    'def countdown(n):\n'
                    '    if n <= 0:\n'
                    '        print("Liftoff!")\n'
                    '        return\n'
                    '    print(f"  {n}...")\n'
                    '    countdown(n - 1)\n'
                    '\n'
                    'print("\\nCountdown:")\n'
                    'countdown(5)\n'
                ),
            },
            {
                "name": "Lambda & Map/Filter",
                "desc": "Anonymous functions and data transforms",
                "code": (
                    '# Lambda & Map/Filter\n'
                    '# Lambda creates small one-line functions.\n'
                    '# map() and filter() apply functions to sequences.\n'
                    '\n'
                    '# A lambda is a function without a name\n'
                    '# Normal function:\n'
                    'def double(x):\n'
                    '    return x * 2\n'
                    '\n'
                    '# Same thing as a lambda:\n'
                    'double_lambda = lambda x: x * 2\n'
                    '\n'
                    'print(f"double(5) = {double(5)}")\n'
                    'print(f"lambda(5) = {double_lambda(5)}")\n'
                    '\n'
                    '# === map() — apply a function to every item ===\n'
                    'numbers = [1, 2, 3, 4, 5]\n'
                    'doubled = list(map(lambda x: x * 2, numbers))\n'
                    'print(f"\\nOriginal: {numbers}")\n'
                    'print(f"Doubled:  {doubled}")\n'
                    '\n'
                    '# === filter() — keep only items that pass a test ===\n'
                    'numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n'
                    'evens = list(filter(lambda x: x % 2 == 0, numbers))\n'
                    'print(f"\\nAll:   {numbers}")\n'
                    'print(f"Evens: {evens}")\n'
                    '\n'
                    '# === Sorting with lambda ===\n'
                    '# Sort a list of tuples by the second element\n'
                    'scores = [("Alice", 92), ("Bob", 85), ("Charlie", 95)]\n'
                    'by_score = sorted(scores, key=lambda pair: pair[1], reverse=True)\n'
                    'print("\\nRanked by score:")\n'
                    'for name, score in by_score:\n'
                    '    print(f"  {name}: {score}")\n'
                ),
            },
            {
                "name": "Decorators",
                "desc": "Wrapping functions to add behavior",
                "code": (
                    '# Decorators\n'
                    '# A decorator wraps a function to add extra behavior\n'
                    '# without changing the original function\'s code.\n'
                    '\n'
                    'import time\n'
                    '\n'
                    '# === Building a decorator step by step ===\n'
                    '# A decorator is just a function that takes a function\n'
                    '# and returns a new function.\n'
                    '\n'
                    'def timer(func):\n'
                    '    """Measure how long a function takes to run."""\n'
                    '    def wrapper(*args, **kwargs):\n'
                    '        start = time.time()\n'
                    '        result = func(*args, **kwargs)\n'
                    '        elapsed = time.time() - start\n'
                    '        print(f"  {func.__name__} took {elapsed:.4f} seconds")\n'
                    '        return result\n'
                    '    return wrapper\n'
                    '\n'
                    '# Apply it with the @ symbol\n'
                    '@timer\n'
                    'def slow_add(a, b):\n'
                    '    time.sleep(0.1)  # Simulate slow work\n'
                    '    return a + b\n'
                    '\n'
                    'print(f"Result: {slow_add(3, 5)}")\n'
                    '\n'
                    '# === Another example: a repeat decorator ===\n'
                    'def repeat(n):\n'
                    '    """Run a function n times."""\n'
                    '    def decorator(func):\n'
                    '        def wrapper(*args, **kwargs):\n'
                    '            for i in range(n):\n'
                    '                result = func(*args, **kwargs)\n'
                    '            return result\n'
                    '        return wrapper\n'
                    '    return decorator\n'
                    '\n'
                    '@repeat(3)\n'
                    'def say_hello(name):\n'
                    '    print(f"Hello, {name}!")\n'
                    '\n'
                    'print()\n'
                    'say_hello("Alice")  # Prints 3 times!\n'
                ),
            },
        ],
    },
    {
        "name": "File I/O",
        "icon": "\U0001F4C4",
        "examples": [
            {
                "name": "Reading & Writing Files",
                "desc": "Saving and loading text files",
                "code": (
                    '# Reading & Writing Files\n'
                    '# Python can create, write to, and read text files.\n'
                    '\n'
                    '# === Writing a file ===\n'
                    '# "w" mode creates/overwrites the file\n'
                    '# "with" automatically closes the file when done\n'
                    'with open("example.txt", "w") as f:\n'
                    '    f.write("Hello, file!\\n")\n'
                    '    f.write("This is line 2.\\n")\n'
                    '    f.write("Python is fun!\\n")\n'
                    '\n'
                    'print("File written!")\n'
                    '\n'
                    '# === Reading the whole file ===\n'
                    'with open("example.txt", "r") as f:\n'
                    '    content = f.read()\n'
                    'print("\\n--- Full content ---")\n'
                    'print(content)\n'
                    '\n'
                    '# === Reading line by line ===\n'
                    'print("--- Line by line ---")\n'
                    'with open("example.txt", "r") as f:\n'
                    '    for line_num, line in enumerate(f, 1):\n'
                    '        # .strip() removes the newline at the end\n'
                    '        print(f"Line {line_num}: {line.strip()}")\n'
                    '\n'
                    '# === Appending to a file ===\n'
                    '# "a" mode adds to the end without erasing\n'
                    'with open("example.txt", "a") as f:\n'
                    '    f.write("This line was appended!\\n")\n'
                    '\n'
                    '# Read again to confirm\n'
                    'with open("example.txt", "r") as f:\n'
                    '    lines = f.readlines()  # Returns a list of lines\n'
                    'print(f"\\nFile now has {len(lines)} lines.")\n'
                ),
            },
            {
                "name": "CSV Files",
                "desc": "Working with spreadsheet-style data",
                "code": (
                    '# CSV Files\n'
                    '# CSV = Comma-Separated Values, a common data format.\n'
                    '# Think of it like a simple spreadsheet.\n'
                    '\n'
                    'import csv\n'
                    '\n'
                    '# === Writing a CSV file ===\n'
                    'students = [\n'
                    '    ["Name", "Age", "Grade"],  # Header row\n'
                    '    ["Alice", 14, "A"],\n'
                    '    ["Bob", 15, "B+"],\n'
                    '    ["Charlie", 14, "A-"],\n'
                    ']\n'
                    '\n'
                    'with open("students.csv", "w", newline="") as f:\n'
                    '    writer = csv.writer(f)\n'
                    '    writer.writerows(students)  # Write all rows at once\n'
                    'print("CSV file written!")\n'
                    '\n'
                    '# === Reading a CSV file ===\n'
                    'print("\\nReading students.csv:")\n'
                    'with open("students.csv", "r") as f:\n'
                    '    reader = csv.reader(f)\n'
                    '    header = next(reader)  # First row is the header\n'
                    '    print(f"  Columns: {header}")\n'
                    '    for row in reader:\n'
                    '        print(f"  {row[0]:10} Age: {row[1]}  Grade: {row[2]}")\n'
                    '\n'
                    '# === Using DictReader for named columns ===\n'
                    'print("\\nWith DictReader:")\n'
                    'with open("students.csv", "r") as f:\n'
                    '    reader = csv.DictReader(f)\n'
                    '    for row in reader:\n'
                    '        # Access columns by name instead of index!\n'
                    '        print(f"  {row[\'Name\']} is {row[\'Age\']} and got {row[\'Grade\']}")\n'
                ),
            },
            {
                "name": "JSON Files",
                "desc": "Saving and loading structured data",
                "code": (
                    '# JSON Files\n'
                    '# JSON is a popular format for structured data.\n'
                    '# Python dicts and lists map perfectly to JSON.\n'
                    '\n'
                    'import json\n'
                    '\n'
                    '# Some data to save\n'
                    'game_save = {\n'
                    '    "player": "Hero123",\n'
                    '    "level": 7,\n'
                    '    "health": 85,\n'
                    '    "inventory": ["sword", "shield", "potion"],\n'
                    '    "position": {"x": 42, "y": 108}\n'
                    '}\n'
                    '\n'
                    '# === Save to JSON file ===\n'
                    'with open("savegame.json", "w") as f:\n'
                    '    # indent=2 makes the file human-readable\n'
                    '    json.dump(game_save, f, indent=2)\n'
                    'print("Game saved!")\n'
                    '\n'
                    '# === Load from JSON file ===\n'
                    'with open("savegame.json", "r") as f:\n'
                    '    loaded = json.load(f)\n'
                    '\n'
                    'print(f"\\nLoaded save for: {loaded[\'player\']}")\n'
                    'print(f"Level: {loaded[\'level\']}")\n'
                    'print(f"Health: {loaded[\'health\']}")\n'
                    'print(f"Items: {\\", \\".join(loaded[\'inventory\'])}")\n'
                    'print(f"Position: ({loaded[\'position\'][\'x\']}, {loaded[\'position\'][\'y\']})")\n'
                    '\n'
                    '# === Convert to/from JSON strings ===\n'
                    'data = {"name": "Alice", "scores": [95, 87, 92]}\n'
                    'json_string = json.dumps(data)  # Dict -> JSON string\n'
                    'print(f"\\nJSON string: {json_string}")\n'
                    '\n'
                    'back_to_dict = json.loads(json_string)  # JSON string -> Dict\n'
                    'print(f"Back to dict: {back_to_dict}")\n'
                ),
            },
        ],
    },
    {
        "name": "Classes & Objects",
        "icon": "\U0001F3D7",
        "examples": [
            {
                "name": "Basic Classes",
                "desc": "Creating your own types with classes",
                "code": (
                    '# Basic Classes\n'
                    '# A class is a blueprint for creating objects.\n'
                    '# Objects bundle data (attributes) and actions (methods).\n'
                    '\n'
                    'class Dog:\n'
                    '    # __init__ runs when you create a new Dog\n'
                    '    # "self" refers to the specific dog being created\n'
                    '    def __init__(self, name, breed):\n'
                    '        self.name = name      # Store the name\n'
                    '        self.breed = breed    # Store the breed\n'
                    '        self.tricks = []      # Start with no tricks\n'
                    '\n'
                    '    def learn_trick(self, trick):\n'
                    '        """Teach the dog a new trick."""\n'
                    '        self.tricks.append(trick)\n'
                    '        print(f"{self.name} learned {trick}!")\n'
                    '\n'
                    '    def show_tricks(self):\n'
                    '        """Display all tricks the dog knows."""\n'
                    '        if self.tricks:\n'
                    '            tricks_str = ", ".join(self.tricks)\n'
                    '            print(f"{self.name} knows: {tricks_str}")\n'
                    '        else:\n'
                    '            print(f"{self.name} doesn\'t know any tricks yet.")\n'
                    '\n'
                    '    def __str__(self):\n'
                    '        """This controls what print() shows."""\n'
                    '        return f"{self.name} the {self.breed}"\n'
                    '\n'
                    '\n'
                    '# Create Dog objects\n'
                    'buddy = Dog("Buddy", "Golden Retriever")\n'
                    'max_dog = Dog("Max", "Beagle")\n'
                    '\n'
                    'print(buddy)  # Uses __str__\n'
                    'print(max_dog)\n'
                    '\n'
                    '# Teach some tricks\n'
                    'buddy.learn_trick("sit")\n'
                    'buddy.learn_trick("shake")\n'
                    'max_dog.learn_trick("roll over")\n'
                    '\n'
                    'print()\n'
                    'buddy.show_tricks()\n'
                    'max_dog.show_tricks()\n'
                ),
            },
            {
                "name": "Inheritance",
                "desc": "Building new classes from existing ones",
                "code": (
                    '# Inheritance\n'
                    '# A child class can inherit from a parent class,\n'
                    '# reusing its code and adding new features.\n'
                    '\n'
                    '# Parent class\n'
                    'class Animal:\n'
                    '    def __init__(self, name, sound):\n'
                    '        self.name = name\n'
                    '        self.sound = sound\n'
                    '\n'
                    '    def speak(self):\n'
                    '        print(f"{self.name} says {self.sound}!")\n'
                    '\n'
                    '    def __str__(self):\n'
                    '        return self.name\n'
                    '\n'
                    '\n'
                    '# Child class — inherits from Animal\n'
                    'class Cat(Animal):\n'
                    '    def __init__(self, name, indoor=True):\n'
                    '        # super() calls the parent\'s __init__\n'
                    '        super().__init__(name, "Meow")\n'
                    '        self.indoor = indoor\n'
                    '\n'
                    '    def purr(self):\n'
                    '        """Only cats can purr — this is a new method."""\n'
                    '        print(f"{self.name} purrs softly...")\n'
                    '\n'
                    '\n'
                    'class Dog(Animal):\n'
                    '    def __init__(self, name, breed):\n'
                    '        super().__init__(name, "Woof")\n'
                    '        self.breed = breed\n'
                    '\n'
                    '    def fetch(self, item):\n'
                    '        print(f"{self.name} fetches the {item}!")\n'
                    '\n'
                    '\n'
                    '# Create animals\n'
                    'whiskers = Cat("Whiskers", indoor=True)\n'
                    'rex = Dog("Rex", "German Shepherd")\n'
                    '\n'
                    '# Both can use the parent\'s speak() method\n'
                    'whiskers.speak()  # Whiskers says Meow!\n'
                    'rex.speak()       # Rex says Woof!\n'
                    '\n'
                    '# Each has its own special methods\n'
                    'whiskers.purr()\n'
                    'rex.fetch("ball")\n'
                    '\n'
                    '# isinstance() checks if an object is a certain type\n'
                    'print(f"\\nIs whiskers a Cat? {isinstance(whiskers, Cat)}")\n'
                    'print(f"Is whiskers an Animal? {isinstance(whiskers, Animal)}")\n'
                    'print(f"Is rex a Cat? {isinstance(rex, Cat)}")\n'
                ),
            },
            {
                "name": "Magic Methods",
                "desc": "Customizing how objects behave",
                "code": (
                    '# Magic Methods (Dunder Methods)\n'
                    '# Special methods like __add__, __len__, __eq__ let you\n'
                    '# control how your objects work with Python operators.\n'
                    '\n'
                    'class Vector:\n'
                    '    """A 2D vector with x and y components."""\n'
                    '\n'
                    '    def __init__(self, x, y):\n'
                    '        self.x = x\n'
                    '        self.y = y\n'
                    '\n'
                    '    def __repr__(self):\n'
                    '        """How the vector looks when printed."""\n'
                    '        return f"Vector({self.x}, {self.y})"\n'
                    '\n'
                    '    def __add__(self, other):\n'
                    '        """v1 + v2 adds the components."""\n'
                    '        return Vector(self.x + other.x, self.y + other.y)\n'
                    '\n'
                    '    def __mul__(self, scalar):\n'
                    '        """v * 3 scales the vector."""\n'
                    '        return Vector(self.x * scalar, self.y * scalar)\n'
                    '\n'
                    '    def __eq__(self, other):\n'
                    '        """v1 == v2 checks if components match."""\n'
                    '        return self.x == other.x and self.y == other.y\n'
                    '\n'
                    '    def __abs__(self):\n'
                    '        """abs(v) returns the length of the vector."""\n'
                    '        return (self.x ** 2 + self.y ** 2) ** 0.5\n'
                    '\n'
                    '\n'
                    '# Now we can use +, *, ==, abs() with Vectors!\n'
                    'a = Vector(3, 4)\n'
                    'b = Vector(1, 2)\n'
                    '\n'
                    'print(f"a = {a}")\n'
                    'print(f"b = {b}")\n'
                    'print(f"a + b = {a + b}")\n'
                    'print(f"a * 3 = {a * 3}")\n'
                    'print(f"a == b: {a == b}")\n'
                    'print(f"a == Vector(3, 4): {a == Vector(3, 4)}")\n'
                    'print(f"|a| = {abs(a):.2f}")  # 3-4-5 triangle!\n'
                ),
            },
            {
                "name": "Dataclasses",
                "desc": "Simple classes with less boilerplate",
                "code": (
                    '# Dataclasses\n'
                    '# The @dataclass decorator auto-generates __init__,\n'
                    '# __repr__, __eq__, and more — less typing!\n'
                    '\n'
                    'from dataclasses import dataclass, field\n'
                    '\n'
                    '# === Without dataclass (lots of boilerplate) ===\n'
                    '# class Point:\n'
                    '#     def __init__(self, x, y):\n'
                    '#         self.x = x\n'
                    '#         self.y = y\n'
                    '#     def __repr__(self): ...\n'
                    '#     def __eq__(self, other): ...\n'
                    '\n'
                    '# === With dataclass (clean and simple!) ===\n'
                    '@dataclass\n'
                    'class Point:\n'
                    '    x: float\n'
                    '    y: float\n'
                    '\n'
                    'p1 = Point(3, 4)\n'
                    'p2 = Point(3, 4)\n'
                    'p3 = Point(1, 2)\n'
                    '\n'
                    'print(f"p1 = {p1}")           # Auto __repr__\n'
                    'print(f"p1 == p2: {p1 == p2}") # Auto __eq__\n'
                    'print(f"p1 == p3: {p1 == p3}")\n'
                    '\n'
                    '# === Default values and fields ===\n'
                    '@dataclass\n'
                    'class Student:\n'
                    '    name: str\n'
                    '    age: int\n'
                    '    grade: str = "N/A"              # Default value\n'
                    '    courses: list = field(default_factory=list)  # Mutable default\n'
                    '\n'
                    '    def is_passing(self):\n'
                    '        return self.grade not in ("F", "N/A")\n'
                    '\n'
                    'alice = Student("Alice", 15, "A")\n'
                    'bob = Student("Bob", 14)  # Uses defaults\n'
                    '\n'
                    'alice.courses.append("Math")\n'
                    'alice.courses.append("Science")\n'
                    '\n'
                    'print(f"\\n{alice}")\n'
                    'print(f"Passing: {alice.is_passing()}")\n'
                    'print(f"Courses: {alice.courses}")\n'
                    '\n'
                    'print(f"\\n{bob}")\n'
                    'print(f"Passing: {bob.is_passing()}")\n'
                    'print(f"Courses: {bob.courses}")  # Empty — not shared!\n'
                ),
            },
        ],
    },
    {
        "name": "Fun Projects",
        "icon": "\U0001F3AE",
        "examples": [
            {
                "name": "Rock Paper Scissors",
                "desc": "A classic game against the computer",
                "code": (
                    '# Rock Paper Scissors\n'
                    '# Play against the computer!\n'
                    '\n'
                    'import random\n'
                    '\n'
                    'choices = ["rock", "paper", "scissors"]\n'
                    'wins = 0\n'
                    'losses = 0\n'
                    '\n'
                    'print("=== Rock Paper Scissors ===")\n'
                    'print("Type rock, paper, or scissors (or quit to stop)\\n")\n'
                    '\n'
                    'while True:\n'
                    '    player = input("Your choice: ").strip().lower()\n'
                    '\n'
                    '    if player == "quit":\n'
                    '        break\n'
                    '\n'
                    '    if player not in choices:\n'
                    '        print("Invalid choice! Try rock, paper, or scissors.")\n'
                    '        continue\n'
                    '\n'
                    '    computer = random.choice(choices)\n'
                    '    print(f"Computer chose: {computer}")\n'
                    '\n'
                    '    if player == computer:\n'
                    '        print("It\'s a tie!\\n")\n'
                    '    elif (\n'
                    '        (player == "rock" and computer == "scissors") or\n'
                    '        (player == "paper" and computer == "rock") or\n'
                    '        (player == "scissors" and computer == "paper")\n'
                    '    ):\n'
                    '        print("You win!\\n")\n'
                    '        wins += 1\n'
                    '    else:\n'
                    '        print("You lose!\\n")\n'
                    '        losses += 1\n'
                    '\n'
                    'print(f"\\nFinal score: {wins} wins, {losses} losses")\n'
                ),
            },
            {
                "name": "Password Generator",
                "desc": "Generate secure random passwords",
                "code": (
                    '# Password Generator\n'
                    '# Creates random passwords of any length.\n'
                    '\n'
                    'import random\n'
                    'import string\n'
                    '\n'
                    '# string module gives us character sets\n'
                    '# string.ascii_letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"\n'
                    '# string.digits = "0123456789"\n'
                    '# string.punctuation = "!@#$%^&*()..." etc.\n'
                    '\n'
                    'def generate_password(length=12, use_symbols=True):\n'
                    '    """Generate a random password of the given length."""\n'
                    '    characters = string.ascii_letters + string.digits\n'
                    '    if use_symbols:\n'
                    '        characters += string.punctuation\n'
                    '\n'
                    '    # random.choices() picks random items from a sequence\n'
                    '    password = "".join(random.choices(characters, k=length))\n'
                    '    return password\n'
                    '\n'
                    '\n'
                    'print("=== Password Generator ===")\n'
                    'print()\n'
                    '\n'
                    'length = int(input("Password length (default 12): ") or "12")\n'
                    'count = int(input("How many passwords? (default 5): ") or "5")\n'
                    'symbols = input("Include symbols? (y/n, default y): ").strip().lower()\n'
                    'use_symbols = symbols != "n"\n'
                    '\n'
                    'print(f"\\nGenerated passwords ({length} chars):")\n'
                    'for i in range(count):\n'
                    '    pwd = generate_password(length, use_symbols)\n'
                    '    print(f"  {i + 1}. {pwd}")\n'
                ),
            },
            {
                "name": "Word Counter",
                "desc": "Analyze text and count word frequency",
                "code": (
                    '# Word Counter\n'
                    '# Counts how often each word appears in text.\n'
                    '\n'
                    'text = """\n'
                    'Python is a great programming language.\n'
                    'Python is easy to learn and fun to use.\n'
                    'Many people love Python because it is simple.\n'
                    '"""\n'
                    '\n'
                    '# Clean up the text\n'
                    '# .lower() makes everything lowercase\n'
                    '# .split() breaks text into a list of words\n'
                    'words = text.lower().split()\n'
                    '\n'
                    '# Remove punctuation from each word\n'
                    'clean_words = []\n'
                    'for word in words:\n'
                    '    # .strip() removes characters from the edges\n'
                    "    cleaned = word.strip('.,!?;:\\'\"')\n"
                    '    if cleaned:  # Skip empty strings\n'
                    '        clean_words.append(cleaned)\n'
                    '\n'
                    '# Count each word using a dictionary\n'
                    'word_counts = {}\n'
                    'for word in clean_words:\n'
                    '    if word in word_counts:\n'
                    '        word_counts[word] += 1\n'
                    '    else:\n'
                    '        word_counts[word] = 1\n'
                    '\n'
                    '# Sort by count (most common first)\n'
                    '# sorted() with key= tells Python how to sort\n'
                    'sorted_words = sorted(word_counts.items(),\n'
                    '                      key=lambda pair: pair[1],\n'
                    '                      reverse=True)\n'
                    '\n'
                    'print(f"Total words: {len(clean_words)}")\n'
                    'print(f"Unique words: {len(word_counts)}")\n'
                    'print("\\nWord frequencies:")\n'
                    'for word, count in sorted_words:\n'
                    '    bar = "#" * count  # Visual bar\n'
                    '    print(f"  {word:12} {count:2} {bar}")\n'
                ),
            },
            {
                "name": "Hangman",
                "desc": "Classic word guessing game",
                "code": (
                    '# Hangman\n'
                    '# Guess the hidden word one letter at a time!\n'
                    '\n'
                    'import random\n'
                    '\n'
                    'words = ["python", "coding", "function", "variable", "string"]\n'
                    'secret = random.choice(words)\n'
                    'guessed = set()      # Letters the player has guessed\n'
                    'max_wrong = 6        # Number of wrong guesses allowed\n'
                    'wrong = 0\n'
                    '\n'
                    'print("=== Hangman ===")\n'
                    'print(f"The word has {len(secret)} letters.\\n")\n'
                    '\n'
                    'while wrong < max_wrong:\n'
                    '    # Show the word with blanks for unguessed letters\n'
                    '    display = ""\n'
                    '    for letter in secret:\n'
                    '        if letter in guessed:\n'
                    '            display += letter + " "\n'
                    '        else:\n'
                    '            display += "_ "\n'
                    '    print(f"Word: {display}")\n'
                    '    print(f"Wrong guesses left: {max_wrong - wrong}")\n'
                    '    print(f"Guessed: {\\", \\".join(sorted(guessed)) or \\"none\\"}")\n'
                    '\n'
                    '    # Check if the player won\n'
                    '    if all(letter in guessed for letter in secret):\n'
                    '        print(f"\\nYou win! The word was \\"{secret}\\"!")\n'
                    '        break\n'
                    '\n'
                    '    # Get a guess\n'
                    '    guess = input("\\nGuess a letter: ").lower().strip()\n'
                    '    if len(guess) != 1 or not guess.isalpha():\n'
                    '        print("Please enter a single letter.")\n'
                    '        continue\n'
                    '    if guess in guessed:\n'
                    '        print("You already guessed that!")\n'
                    '        continue\n'
                    '\n'
                    '    guessed.add(guess)\n'
                    '    if guess in secret:\n'
                    '        print(f"Correct! \\"{guess}\\" is in the word!")\n'
                    '    else:\n'
                    '        wrong += 1\n'
                    '        print(f"Wrong! \\"{guess}\\" is not in the word.")\n'
                    '    print()\n'
                    'else:\n'
                    '    print(f"\\nGame over! The word was \\"{secret}\\".")\n'
                ),
            },
            {
                "name": "Dice Roller",
                "desc": "Simulate dice rolls with statistics",
                "code": (
                    '# Dice Roller\n'
                    '# Roll dice and see the statistics!\n'
                    '\n'
                    'import random\n'
                    '\n'
                    'def roll_dice(num_dice=2, sides=6):\n'
                    '    """Roll some dice and return the results."""\n'
                    '    rolls = [random.randint(1, sides) for _ in range(num_dice)]\n'
                    '    return rolls\n'
                    '\n'
                    '# Roll a pair of dice\n'
                    'print("=== Dice Roller ===")\n'
                    'dice = roll_dice(2, 6)\n'
                    'print(f"You rolled: {dice[0]} and {dice[1]}")\n'
                    'print(f"Total: {sum(dice)}")\n'
                    '\n'
                    '# Roll many times and track the results\n'
                    'num_rolls = 1000\n'
                    'totals = {}\n'
                    'for _ in range(num_rolls):\n'
                    '    total = sum(roll_dice(2, 6))\n'
                    '    totals[total] = totals.get(total, 0) + 1\n'
                    '\n'
                    'print(f"\\nRolling 2 dice {num_rolls} times:")\n'
                    'print(f"{\'Total\':>6} {\'Count\':>6} {\'Pct\':>6}  Distribution")\n'
                    'print("-" * 50)\n'
                    'for value in range(2, 13):\n'
                    '    count = totals.get(value, 0)\n'
                    '    pct = count / num_rolls * 100\n'
                    '    bar = "#" * int(pct)\n'
                    '    print(f"{value:>6} {count:>6} {pct:>5.1f}%  {bar}")\n'
                    '\n'
                    'print(f"\\n7 is the most common total because there")\n'
                    'print(f"are the most ways to make it (1+6, 2+5, 3+4, etc.)")\n'
                ),
            },
        ],
    },
]
